<img src="img2/Banner Curso 1_.jpg" width="921" height="89" align="center"/>

<h1><center>Introducción a la ciencia de datos con Python - AnáhuacX</center></h1>
<h2><center>Actividad 2</center></h2>

La pobreza es un tema de suma relevancia para la agenda de todos los gobiernos alrededor del mundo. Los esfuerzos de múltiples naciones se han consolidado en los __Objetivos de Desarrollo Sostenible__ propuestos por la ONU, organización de la que México y muchos países de latinoamérica forman parte. Conocer la magnitud del problema es prioridad en orden para proponer intervenciones eficaces que abonen a disminuir la brecha de desigualdad.

<img src="img2/S-SDG-Poster_-Letter.jpg" width="800" height="800" align="center"/>

__En la siguiente actividad limpiarás y explorarás un dataframe en el que encontrarás datos relevantes al análisis de la pobreza en los diferentes países que integran a la Organización de las Naciones Unidas.__

<br>
<br>
<br>


1. Importa las librerías de Pandas, Numpy, Requests, Webbrowser y Beautiful soup a tu libreta. Las estaremos utilizando a lo largo del ejercicio.

In [3]:
import pandas as pd

import numpy as np

import requests

import webbrowser

from bs4 import BeautifulSoup

2. Accede a la siguiente página web desde tu libreta utilizando webbrowser. 

_https://en.wikipedia.org/wiki/List_of_countries_by_percentage_of_population_living_in_poverty_

In [4]:
webbrowser.open('https://en.wikipedia.org/wiki/List_of_countries_by_percentage_of_population_living_in_poverty')

True

3. Descarga en tu libreta la página proporcionada y obtén todas las tablas utilizando la librería requests y beautiful soup. Recuerda escribir el número de tabla correcto. Te recomendamos explorar la página.

In [5]:
res = requests.get('https://en.wikipedia.org/wiki/List_of_countries_by_percentage_of_population_living_in_poverty')

res

<Response [200]>

In [6]:
soup = BeautifulSoup(res.content)
table = soup.find_all('table')

4. Utilizando la función “read_html” de la librería “Pandas” guarda la tabla __"Percent of population (including non-citizens) living under \\$1,90, \\$3,20 and \\$5,50 a day"__ en una variable llamada “df”. 

_Sugerencia: Ocupa la función "head" de la librería "Pandas" para mostrar los primeros cinco elementos y verificar que haya funcionado lo anterior._

In [7]:
df = pd.read_html(str(table))
df = df[0]

In [8]:
df.head()

Country < $1.90[8][1] < $3.20[6] < $5.50[7]  Year      Continent
0    Albania          1.3%       8.2%      33.8%  2017         Europe
1    Algeria          0.4%       3.7%      28.6%  2011         Africa
2     Angola         49.9%      72.0%      89.3%  2018         Africa
3  Argentina          1.5%       5.0%      14.0%  2019  South America
4    Armenia          1.1%      10.0%      44.0%  2019           Asia

5. __¿Cuántas filas tiene el dataframe?__ Recuerda utilizar tu libreta de Python para encontrar la respuesta.

6. __¿Cuántas columnas posee el dataframe?__

In [9]:
df.shape

(164, 6)

7.	Debido a que los datos de la tabla contienen registros vacíos y el símbolo de porcentaje, es necesario que realices una limpieza de estos datos; utiliza las funciones __"replace"__ y __"dropna"__ de "Pandas" para lograrlo. 

__Ejemplo de sintaxis de la función "replace": df = df.replace({'%':""}, regex = True).__ (Se sugiere utilizar la función "head" con la tabla  modificada para visualizar que todo se encuentre en orden).

__¿Cuántas filas quedaron después de hacer esto?__

In [10]:
df = df.replace({'%':""}, regex = True)

In [11]:
df.head()

Country < $1.90[8][1] < $3.20[6] < $5.50[7]  Year      Continent
0    Albania           1.3        8.2       33.8  2017         Europe
1    Algeria           0.4        3.7       28.6  2011         Africa
2     Angola          49.9       72.0       89.3  2018         Africa
3  Argentina           1.5        5.0       14.0  2019  South America
4    Armenia           1.1       10.0       44.0  2019           Asia

8.	Verifica el tipo de datos que poseen las columnas de tu dataframe utilizando la función __“info”__. (Puedes encontrar más información acerca de cómo utilizar esta función a través del siguiente link: https://www.geeksforgeeks.org/python-pandas-dataframe-info/ 

__¿Cuál es el tipo de datos que aparece en la mayoría de las columnas?__

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Country        164 non-null    object
 1   < $1.90[8][1]  164 non-null    object
 2   < $3.20[6]     164 non-null    object
 3   < $5.50[7]     164 non-null    object
 4   Year           164 non-null    int64 
 5   Continent      164 non-null    object
dtypes: int64(1), object(5)
memory usage: 7.8+ KB


9.	Transforma las columnas “< \\$1.90[1]”, “< \\$3.20[5]”, “< \\$5.50[6]” a tipo __flotante__ para que puedas hacer análisis con ellas. Para esto te recomendamos utilizar la función __“astype”__. Para más información te recomendamos entrar a el siguiente vínculo: 

https://www.geeksforgeeks.org/python-pandas-dataframe-astype/#:~:text=astype()%20method%20is%20used,type%20to%20another%20data%20type. 

In [13]:
#Cambio de nombre de las columnas
df.rename(columns={'< $1.90[8][1]': '$1.90','< $3.20[6]': '$3.20', '< $5.50[7]':'$5.50'}, inplace=True)

#Imprimimos el resultado de la transformacion de las columnas
df

Country $1.90 $3.20 $5.50  Year      Continent
0      Albania   1.3   8.2  33.8  2017         Europe
1      Algeria   0.4   3.7  28.6  2011         Africa
2       Angola  49.9  72.0  89.3  2018         Africa
3    Argentina   1.5   5.0  14.0  2019  South America
4      Armenia   1.1  10.0  44.0  2019           Asia
..         ...   ...   ...   ...   ...            ...
159  Venezuela   6.7  14.0  33.0  2006  South America
160    Vietnam   1.8   7.0  22.0  2018           Asia
161      Yemen  18.3  51.0  81.6  2014           Asia
162     Zambia  58.7  75.0  88.0  2015         Africa
163   Zimbabwe  39.5  64.0  83.0  2019         Africa

[164 rows x 6 columns]

In [14]:
#Empezamos la conversion de las columnas "$1.90, $3.20, $5.50" a float.
df['$5.50'] = df['$5.50'].astype(float)

df.dtypes

Country       object
$1.90         object
$3.20         object
$5.50        float64
Year           int64
Continent     object
dtype: object

In [15]:
#Empezamos la conversion de las columnas "$3.20"  a float.
df['$3.20'] = df['$3.20'].astype(float)
df.dtypes

Country       object
$1.90         object
$3.20        float64
$5.50        float64
Year           int64
Continent     object
dtype: object

In [16]:
#Empezamos la conversion de las columnas "$1.90"  a str.
df['$1.90'] = df['$1.90'].convert_dtypes(str)
df.dtypes

Country       object
$1.90         string
$3.20        float64
$5.50        float64
Year           int64
Continent     object
dtype: object

In [17]:
 #Empezamos la conversion de las columnas "$1.90"  a float.
df['$1.90'] = df['$1.90'].astype(float)

ValueError: could not convert string to float: '10.6[11]'

In [18]:
#Buscamos el valor 10.6[11] para poderlo limpiar
df.head(66)

Country     $1.90  $3.20  $5.50  Year      Continent
0     Albania       1.3    8.2   33.8  2017         Europe
1     Algeria       0.4    3.7   28.6  2011         Africa
2      Angola      49.9   72.0   89.3  2018         Africa
3   Argentina       1.5    5.0   14.0  2019  South America
4     Armenia       1.1   10.0   44.0  2019           Asia
..        ...       ...    ...    ...   ...            ...
61    Hungary       0.2    0.6    2.0  2018         Europe
62    Iceland       0.0    0.0    0.2  2017         Europe
63      India  10.6[11]   45.2   79.5  2017           Asia
64  Indonesia       2.7   20.0   42.0  2019           Asia
65       Iran       0.5    2.5   14.0  2018           Asia

[66 rows x 6 columns]

In [19]:
#Ahora vamos a modificar un valor en la columna $1.90 para poder proceder con la transformacion
#[fila:columna]
df['$1.90'] = df['$1.90'].replace(['10.6[11]'], 10.6)
df.head(65)


Country $1.90  $3.20  $5.50  Year      Continent
0     Albania   1.3    8.2   33.8  2017         Europe
1     Algeria   0.4    3.7   28.6  2011         Africa
2      Angola  49.9   72.0   89.3  2018         Africa
3   Argentina   1.5    5.0   14.0  2019  South America
4     Armenia   1.1   10.0   44.0  2019           Asia
..        ...   ...    ...    ...   ...            ...
60   Honduras  14.8   29.0   49.0  2019  North America
61    Hungary   0.2    0.6    2.0  2018         Europe
62    Iceland   0.0    0.0    0.2  2017         Europe
63      India  10.6   45.2   79.5  2017           Asia
64  Indonesia   2.7   20.0   42.0  2019           Asia

[65 rows x 6 columns]

10. Utiliza la función __describe__ en el dataframe y responde __¿Cuál es el promedio del porcentaje de la población que vive con menos de $5,50 dólares al día?__

In [42]:
df['$5.50'].describe

<bound method NDFrame.describe of 0      33.8
1      28.6
2      89.3
3      14.0
4      44.0
       ... 
159    33.0
160    22.0
161    81.6
162    88.0
163    83.0
Name: $5.50, Length: 164, dtype: float64>

In [22]:
df_sum = df['$5.50'].sum()

In [25]:
df_div = df_sum / 164
df_div

39.60426829268293

In [26]:
df['$5.50'].mean()

39.60426829268293

In [ ]:
prom_pob = df['5.50'].sum()
print("Este es el promedio sobre el porcentaje de $5,50: ",prom_pob)

Este es el promedio sobre el porcentaje de $5,50:  6482.699999999999


11.	__¿Cuál es el porcentaje máximo de personas que viven con menos de \\$1,90 dólares al día?__

In [35]:
df.describe()

$3.20       $5.50         Year
count  164.000000  164.000000   164.000000
mean    24.895122   39.604268  2015.731707
std     28.996570   34.737039     3.856470
min      0.000000    0.000000  1992.000000
25%      1.000000    3.850000  2014.000000
50%      9.700000   31.100000  2017.000000
75%     44.300000   73.000000  2018.000000
max     92.000000   98.000000  2021.000000

12. __¿Cuál es el país que posee ese último porcentaje?__

In [16]:
df['Country'].describe()

count         164
unique        164
top       Albania
freq            1
Name: Country, dtype: object

13.	__¿Cuál es el porcentaje de la población en México que gana menos de \\$1,90 dólares al día?__

In [ ]:
df[]

14.	__¿Cuáles son los 5 países que tienen el mayor porcentaje de población que gana menos de \\$1,90 dólares al día?__

In [31]:
df['5.50'].max()

KeyError: '5.50'

15.	Utiliza la función "drop" de "Pandas" para eliminar la columna "year" y así simplificar más tu conjunto de datos.

16.	Utiliza la función “groupby” y contesta la siguiente pregunta __¿Cuál es el porcentaje promedio de la población en Sudamérica que vive con menos de \\$3,20 dólares al día?__

17.	__¿Cuál es el país que está en el lugar 140 de la lista?__

18.	__¿Cuál es el país que posee el 140 como número de índice?__

19.	__¿Cuál es el país de América del sur que tiene menos porcentaje de población ganando \\$1,90 dólares al día?__

20.	__¿Cuál es el país de América del sur que tiene más porcentaje de población ganando \\$1,90 dólares al día?__

21.	__¿Cuál es el país de América del norte que tiene más porcentaje de población ganando \\$5,50 dólares al día?__

22.	__¿Cuál es el país de América del norte que tiene menos porcentaje de población ganando \\$3,20 dólares al día?__

23.	Utiliza la función "to_csv" de "Pandas" para generar un archivo .csv con los datos trabajados. Ejemplo de la sintaxis de la función anterior: df.to_csv("NOMBRE.csv")

24. Guarda tu libreta, tu archivo csv recién creado y colócalos en una carpeta comprimida con extensión __.zip__. Sube el archivo .zip a la plataforma de EdX y califica los ejercicios de tus demás compañeros.
<img src="img3/Anáhuac_edX.png" width="498" height="150" align="center"/>